# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.define "chef-server" do |chef|
    chef.vm.box = "ubuntu/trusty64"
    chef.vm.hostname = "chef-server"
    chef.vm.network :private_network, ip: "192.168.33.15"
    chef.vm.provider "virtualbox" do |vb|
      vb.name = chef.vm.hostname
      vb.cpus = 2
      vb.memory = 2048
    end
  end
end
